version: "3.9"

services:
  app:
    build: .
    volumes:
      - .:/app
    env_file: 
      - ${ENV_FILE_PATH:-.env}
    ports:
      - "5002:8080"
      - "5678:5679"   # debugpyç”¨
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
      - FLASK_DEBUG_ATTACH=1
